"""time change

Revision ID: 1af56fa6e0ba
Revises: 93625ac5adbc
Create Date: 2024-05-11 15:40:00.648876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af56fa6e0ba'
down_revision = '93625ac5adbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.TIME(),
               type_=sa.Interval(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_hills_time'), ['time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hills_time'))
        batch_op.alter_column('time',
               existing_type=sa.Interval(),
               type_=sa.TIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
