"""empty message

Revision ID: 4110fcb34aea
Revises: e5760fba46c8
Create Date: 2024-05-11 16:24:05.628055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4110fcb34aea'
down_revision = 'e5760fba46c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Interval(), nullable=True))
        batch_op.alter_column('distance',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_hills_time'), ['time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hills_time'))
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('distance',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('time')

    # ### end Alembic commands ###
