"""add time

Revision ID: 93625ac5adbc
Revises: b7cd29585329
Create Date: 2024-05-11 15:13:17.325231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93625ac5adbc'
down_revision = 'b7cd29585329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills') as batch_op:
        # Add the 'time' column with a default value of the current time
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=False, server_default=sa.func.now()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills') as batch_op:
        # Drop the 'time' column
        batch_op.drop_column('time')

    # ### end Alembic commands ###
