"""empty message

Revision ID: b7cd29585329
Revises: cff4ca45504e
Create Date: 2024-05-10 14:14:15.561748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cd29585329'
down_revision = 'cff4ca45504e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_hills_user_id_users_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hills_user_id_users_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
