"""init

Revision ID: d65b59ec2b17
Revises: 
Create Date: 2024-05-12 03:25:17.008070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65b59ec2b17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hill_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('hills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hills_distance'), ['distance'], unique=False)
        batch_op.create_index(batch_op.f('ix_hills_height'), ['height'], unique=False)
        batch_op.create_index(batch_op.f('ix_hills_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_hills_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_hills_time'), ['time'], unique=False)
        batch_op.create_index(batch_op.f('ix_hills_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hills_title'))
        batch_op.drop_index(batch_op.f('ix_hills_time'))
        batch_op.drop_index(batch_op.f('ix_hills_longitude'))
        batch_op.drop_index(batch_op.f('ix_hills_latitude'))
        batch_op.drop_index(batch_op.f('ix_hills_height'))
        batch_op.drop_index(batch_op.f('ix_hills_distance'))

    op.drop_table('hills')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('hill_info')
    # ### end Alembic commands ###
