"""empty message

Revision ID: e1b6eea1d064
Revises: 8d361cd72ca4
Create Date: 2024-05-12 02:09:40.561063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b6eea1d064'
down_revision = '8d361cd72ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hills', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=20),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
